export const citiesArray: string[] = [
  '3435910',
  '2988507',
  '292223',
  '2147714',
  '1850144',
  '1261481',
  '3451190',
  '2643743',
];

export const simbolos: object | any = {
  metric: 'ºC',
  imperial: 'ºF',
  kelvin: 'ºK',
};

export const countriesMap: object[] = [
  { value: 'AF', label: 'Afganistán' },
  { value: 'AL', label: 'Albania' },
  { value: 'DE', label: 'Alemania' },
  { value: 'AD', label: 'Andorra' },
  { value: 'AO', label: 'Angola' },
  { value: 'AI', label: 'Anguila' },
  { value: 'AQ', label: 'Antártida' },
  { value: 'AG', label: 'Antigua y Barbuda' },
  { value: 'AN', label: 'Antillas holandesas' },
  { value: 'SA', label: 'Arabia Saudí' },
  { value: 'DZ', label: 'Argelia' },
  { value: 'AR', label: 'Argentina' },
  { value: 'AM', label: 'Armenia' },
  { value: 'AW', label: 'Aruba' },
  { value: 'AU', label: 'Australia' },
  { value: 'AT', label: 'Austria' },
  { value: 'AZ', label: 'Azerbaiyán' },
  { value: 'BS', label: 'Bahamas' },
  { value: 'BH', label: 'Bahrein' },
  { value: 'BD', label: 'Bangladesh' },
  { value: 'BB', label: 'Barbados' },
  { value: 'BE', label: 'Bélgica' },
  { value: 'BZ', label: 'Belice' },
  { value: 'BJ', label: 'Benín' },
  { value: 'BM', label: 'Bermudas' },
  { value: 'BT', label: 'Bhután' },
  { value: 'BY', label: 'Bielorrusia' },
  { value: 'MM', label: 'Birmania' },
  { value: 'BO', label: 'Bolivia' },
  { value: 'BA', label: 'Bosnia y Herzegovina' },
  { value: 'BW', label: 'Botsuana' },
  { value: 'BR', label: 'Brasil' },
  { value: 'BN', label: 'Brunei' },
  { value: 'BG', label: 'Bulgaria' },
  { value: 'BF', label: 'Burkina Faso' },
  { value: 'BI', label: 'Burundi' },
  { value: 'CV', label: 'Cabo Verde' },
  { value: 'KH', label: 'Camboya' },
  { value: 'CM', label: 'Camerún' },
  { value: 'CA', label: 'Canadá' },
  { value: 'TD', label: 'Chad' },
  { value: 'CL', label: 'Chile' },
  { value: 'CN', label: 'China' },
  { value: 'CY', label: 'Chipre' },
  { value: 'VA', label: 'Ciudad estado del Vaticano' },
  { value: 'CO', label: 'Colombia' },
  { value: 'KM', label: 'Comores' },
  { value: 'CG', label: 'Congo' },
  { value: 'KR', label: 'Corea' },
  { value: 'KP', label: 'Corea del Norte' },
  { value: 'CI', label: 'Costa del Marfíl' },
  { value: 'CR', label: 'Costa Rica' },
  { value: 'HR', label: 'Croacia' },
  { value: 'CU', label: 'Cuba' },
  { value: 'DK', label: 'Dinamarca' },
  { value: 'DJ', label: 'Djibouri' },
  { value: 'DM', label: 'Dominica' },
  { value: 'EC', label: 'Ecuador' },
  { value: 'EG', label: 'Egipto' },
  { value: 'SV', label: 'El Salvador' },
  { value: 'AE', label: 'Emiratos Arabes Unidos' },
  { value: 'ER', label: 'Eritrea' },
  { value: 'SK', label: 'Eslovaquia' },
  { value: 'SI', label: 'Eslovenia' },
  { value: 'ES', label: 'España' },
  { value: 'US', label: 'Estados Unidos' },
  { value: 'EE', label: 'Estonia' },
  { value: 'ET', label: 'Etiopía' },
  { value: 'MK', label: 'Ex-República Yugoslava de Macedonia' },
  { value: 'PH', label: 'Filipinas' },
  { value: 'FI', label: 'Finlandia' },
  { value: 'FR', label: 'Francia' },
  { value: 'GA', label: 'Gabón' },
  { value: 'GM', label: 'Gambia' },
  { value: 'GE', label: 'Georgia' },
  { value: 'GS', label: 'Georgia del Sur y las islas Sandwich del Sur' },
  { value: 'GH', label: 'Ghana' },
  { value: 'GI', label: 'Gibraltar' },
  { value: 'GD', label: 'Granada' },
  { value: 'GR', label: 'Grecia' },
  { value: 'GL', label: 'Groenlandia' },
  { value: 'GP', label: 'Guadalupe' },
  { value: 'GU', label: 'Guam' },
  { value: 'GT', label: 'Guatemala' },
  { value: 'GY', label: 'Guayana' },
  { value: 'GF', label: 'Guayana francesa' },
  { value: 'GN', label: 'Guinea' },
  { value: 'GQ', label: 'Guinea Ecuatorial' },
  { value: 'GW', label: 'Guinea-Bissau' },
  { value: 'HT', label: 'Haití' },
  { value: 'NL', label: 'Holanda' },
  { value: 'HN', label: 'Honduras' },
  { value: 'HK', label: 'Hong Kong R. A. E' },
  { value: 'HU', label: 'Hungría' },
  { value: 'IN', label: 'India' },
  { value: 'ID', label: 'Indonesia' },
  { value: 'IQ', label: 'Irak' },
  { value: 'IR', label: 'Irán' },
  { value: 'IE', label: 'Irlanda' },
  { value: 'BV', label: 'Isla Bouvet' },
  { value: 'CX', label: 'Isla Christmas' },
  { value: 'HM', label: 'Isla Heard e Islas McDonald' },
  { value: 'IS', label: 'Islandia' },
  { value: 'KY', label: 'Islas Caimán' },
  { value: 'CK', label: 'Islas Cook' },
  { value: 'CC', label: 'Islas de Cocos o Keeling' },
  { value: 'FO', label: 'Islas Faroe' },
  { value: 'FJ', label: 'Islas Fiyi' },
  { value: 'FK', label: 'Islas Malvinas Islas Falkland' },
  { value: 'MP', label: 'Islas Marianas del norte' },
  { value: 'MH', label: 'Islas Marshall' },
  { value: 'UM', label: 'Islas menores de Estados Unidos' },
  { value: 'PW', label: 'Islas Palau' },
  { value: 'SB', label: 'Islas Salomón' },
  { value: 'TK', label: 'Islas Tokelau' },
  { value: 'TC', label: 'Islas Turks y Caicos' },
  { value: 'VI', label: 'Islas Vírgenes EE.UU.' },
  { value: 'VG', label: 'Islas Vírgenes Reino Unido' },
  { value: 'IL', label: 'Israel' },
  { value: 'IT', label: 'Italia' },
  { value: 'JM', label: 'Jamaica' },
  { value: 'JP', label: 'Japón' },
  { value: 'JO', label: 'Jordania' },
  { value: 'KZ', label: 'Kazajistán' },
  { value: 'KE', label: 'Kenia' },
  { value: 'KG', label: 'Kirguizistán' },
  { value: 'KI', label: 'Kiribati' },
  { value: 'KW', label: 'Kuwait' },
  { value: 'LA', label: 'Laos' },
  { value: 'LS', label: 'Lesoto' },
  { value: 'LV', label: 'Letonia' },
  { value: 'LB', label: 'Líbano' },
  { value: 'LR', label: 'Liberia' },
  { value: 'LY', label: 'Libia' },
  { value: 'LI', label: 'Liechtenstein' },
  { value: 'LT', label: 'Lituania' },
  { value: 'LU', label: 'Luxemburgo' },
  { value: 'MO', label: 'Macao R. A. E' },
  { value: 'MG', label: 'Madagascar' },
  { value: 'MY', label: 'Malasia' },
  { value: 'MW', label: 'Malawi' },
  { value: 'MV', label: 'Maldivas' },
  { value: 'ML', label: 'Malí' },
  { value: 'MT', label: 'Malta' },
  { value: 'MA', label: 'Marruecos' },
  { value: 'MQ', label: 'Martinica' },
  { value: 'MU', label: 'Mauricio' },
  { value: 'MR', label: 'Mauritania' },
  { value: 'YT', label: 'Mayotte' },
  { value: 'MX', label: 'México' },
  { value: 'FM', label: 'Micronesia' },
  { value: 'MD', label: 'Moldavia' },
  { value: 'MC', label: 'Mónaco' },
  { value: 'MN', label: 'Mongolia' },
  { value: 'MS', label: 'Montserrat' },
  { value: 'MZ', label: 'Mozambique' },
  { value: 'NA', label: 'Namibia' },
  { value: 'NR', label: 'Nauru' },
  { value: 'NP', label: 'Nepal' },
  { value: 'NI', label: 'Nicaragua' },
  { value: 'NE', label: 'Níger' },
  { value: 'NG', label: 'Nigeria' },
  { value: 'NU', label: 'Niue' },
  { value: 'NF', label: 'Norfolk' },
  { value: 'NO', label: 'Noruega' },
  { value: 'NC', label: 'Nueva Caledonia' },
  { value: 'NZ', label: 'Nueva Zelanda' },
  { value: 'OM', label: 'Omán' },
  { value: 'PA', label: 'Panamá' },
  { value: 'PG', label: 'Papua Nueva Guinea' },
  { value: 'PK', label: 'Paquistán' },
  { value: 'PY', label: 'Paraguay' },
  { value: 'PE', label: 'Perú' },
  { value: 'PN', label: 'Pitcairn' },
  { value: 'PF', label: 'Polinesia francesa' },
  { value: 'PL', label: 'Polonia' },
  { value: 'PT', label: 'Portugal' },
  { value: 'PR', label: 'Puerto Rico' },
  { value: 'QA', label: 'Qatar' },
  { value: 'UK', label: 'Reino Unido' },
  { value: 'CF', label: 'República Centroafricana' },
  { value: 'CZ', label: 'República Checa' },
  { value: 'ZA', label: 'República de Sudáfrica' },
  { value: 'CD', label: 'República Democrática del Congo Zaire' },
  { value: 'DO', label: 'República Dominicana' },
  { value: 'RE', label: 'Reunión' },
  { value: 'RW', label: 'Ruanda' },
  { value: 'RO', label: 'Rumania' },
  { value: 'RU', label: 'Rusia' },
  { value: 'WS', label: 'Samoa' },
  { value: 'AS', label: 'Samoa occidental' },
  { value: 'KN', label: 'San Kitts y Nevis' },
  { value: 'SM', label: 'San Marino' },
  { value: 'PM', label: 'San Pierre y Miquelon' },
  { value: 'VC', label: 'San Vicente e Islas Granadinas' },
  { value: 'SH', label: 'Santa Helena' },
  { value: 'LC', label: 'Santa Lucía' },
  { value: 'ST', label: 'Santo Tomé y Príncipe' },
  { value: 'SN', label: 'Senegal' },
  { value: 'YU', label: 'Serbia y Montenegro' },
  { value: 'SC', label: 'Seychelles' },
  { value: 'SL', label: 'Sierra Leona' },
  { value: 'SG', label: 'Singapur' },
  { value: 'SY', label: 'Siria' },
  { value: 'SO', label: 'Somalia' },
  { value: 'LK', label: 'Sri Lanka' },
  { value: 'SZ', label: 'Suazilandia' },
  { value: 'SD', label: 'Sudán' },
  { value: 'SE', label: 'Suecia' },
  { value: 'CH', label: 'Suiza' },
  { value: 'SR', label: 'Surinam' },
  { value: 'SJ', label: 'Svalbard' },
  { value: 'TH', label: 'Tailandia' },
  { value: 'TW', label: 'Taiwán' },
  { value: 'TZ', label: 'Tanzania' },
  { value: 'TJ', label: 'Tayikistán' },
  { value: 'IO', label: 'Territorios británicos del océano Indico' },
  { value: 'TF', label: 'Territorios franceses del sur' },
  { value: 'TP', label: 'Timor Oriental' },
  { value: 'TG', label: 'Togo' },
  { value: 'TO', label: 'Tonga' },
  { value: 'TT', label: 'Trinidad y Tobago' },
  { value: 'TN', label: 'Túnez' },
  { value: 'TM', label: 'Turkmenistán' },
  { value: 'TR', label: 'Turquía' },
  { value: 'TV', label: 'Tuvalu' },
  { value: 'UA', label: 'Ucrania' },
  { value: 'UG', label: 'Uganda' },
  { value: 'UY', label: 'Uruguay' },
  { value: 'UZ', label: 'Uzbekistán' },
  { value: 'VU', label: 'Vanuatu' },
  { value: 'VE', label: 'Venezuela' },
  { value: 'VN', label: 'Vietnam' },
  { value: 'WF', label: 'Wallis y Futuna' },
  { value: 'YE', label: 'Yemen' },
  { value: 'ZM', label: 'Zambia' },
  { value: 'ZW', label: 'Zimbabue' },
];

export const paises: object | any = {
  AF: 'Afganistán',
  SA: 'Arabia Saudita',
  AL: 'Albania',
  DZ: 'Argelia',
  AD: 'Andorra',
  AO: 'Angola',
  AI: 'Anguila',
  AQ: 'Antártida',
  AG: 'Antigua y Barbuda',
  AR: 'Argentina',
  AM: 'Armenia',
  AW: 'Aruba',
  AU: 'Australia',
  AT: 'Austria',
  AZ: 'Azerbaiyán',
  BS: 'Bahamas',
  BH: 'Baréin',
  BD: 'Bangladesh',
  BB: 'Barbados',
  BY: 'Bielorrusia',
  BE: 'Bélgica',
  BZ: 'Belice',
  BJ: 'Benín',
  BM: 'Bermuda',
  BT: 'Bután',
  BO: 'Bolivia',
  BA: 'Bosnia y Herzegovina',
  BW: 'Botsuana',
  BR: 'Brasil',
  BN: 'Brunei',
  BG: 'Bulgaria',
  BF: 'Burkina Faso',
  BI: 'Burundi',
  KH: 'Camboya',
  CM: 'Camerún',
  CA: 'Canadá',
  CV: 'Cabo Verde',
  TD: 'Chad',
  CL: 'Chile',
  CN: 'China',
  CO: 'Colombia',
  KM: 'Comoras',
  CR: 'Costa Rica',
  HR: 'Croacia',
  CU: 'Cuba',
  CW: 'Curazao',
  CY: 'Chipre',
  DK: 'Dinamarca',
  DM: 'Dominicana',
  EC: 'Ecuador',
  EG: 'Egipto',
  SV: 'El Salvador',
  ER: 'Eritrea',
  EE: 'Estonia',
  ET: 'Etiopía',
  FK: 'Islas Malvinas',
  FO: 'Islas Faroe',
  FJ: 'Fiji',
  FI: 'Finlandia',
  FR: 'Francia',
  GF: 'Guayana Francesa',
  GA: 'Gabón',
  GM: 'Gambia',
  GE: 'Georgia',
  DE: 'Alemania',
  GH: 'Ghana',
  GI: 'Gibraltar',
  GR: 'Grecia',
  GL: 'Groenlandia',
  GD: 'Granada',
  GP: 'Guadalupe',
  GU: 'Guam',
  GT: 'Guatemala',
  GG: 'Guernsey',
  GN: 'Guinea',
  GW: 'Guinea Bissau',
  GY: 'Guyana',
  HT: 'Haití',
  HM: 'Islas Heard y McDonald',
  HN: 'Honduras',
  HK: 'Hong Kong',
  HU: 'Hungría',
  IS: 'Islandia',
  IN: 'India',
  ID: 'Indonesia',
  IR: 'Irán',
  IQ: 'Irak',
  IE: 'Irlanda',
  IM: 'Isla de Man',
  IL: 'Israel',
  IT: 'Italia',
  CI: 'Costa de Marfil',
  JM: 'Jamaica',
  JP: 'Japón',
  JE: 'Jersey',
  JO: 'Jordania',
  KZ: 'Kazajistán',
  KE: 'Kenia',
  KI: 'Kiribati',
  XK: 'Kosovo',
  KW: 'Kuwait',
  KG: 'Kirguistán',
  LA: 'Laos',
  LV: 'Letonia',
  LB: 'Líbano',
  LS: 'Lesoto',
  LR: 'Liberia',
  LY: 'Libia',
  LI: 'Liechtenstein',
  LT: 'Lituania',
  LU: 'Luxemburgo',
  MO: 'Macao',
  MK: 'Macedonia',
  MG: 'Madagascar',
  MW: 'Malaui',
  MY: 'Malasia',
  MV: 'Maldivas',
  ML: 'Malí',
  MT: 'Malta',
  MH: 'Islas Marshall',
  MQ: 'Martinica',
  MR: 'Mauritania',
  MU: 'Mauricio',
  YT: 'Mayotte',
  MX: 'México',
  FM: 'Micronesia',
  MD: 'Moldavia',
  MC: 'Mónaco',
  MN: 'Mongolia',
  ME: 'Montenegro',
  MS: 'Montserrat',
  MA: 'Marruecos',
  MZ: 'Mozambique',
  MM: 'Myanmar',
  NA: 'Namibia',
  NR: 'Nauru',
  NP: 'Nepal',
  NL: 'Países Bajos',
  AN: 'Antillas Holandesas',
  NC: 'Nueva Caledonia',
  NZ: 'Nueva Zelanda',
  NI: 'Nicaragua',
  NE: 'Níger',
  NG: 'Nigeria',
  NU: 'Niue',
  NF: 'Isla Norfolk',
  KP: 'Corea del Norte',
  MP: 'Islas Marianas del Norte',
  NO: 'Noruega',
  OM: 'Omán',
  PK: 'Pakistán',
  PW: 'Palaos',
  PS: 'Territorios Palestinos',
  PA: 'Panamá',
  PG: 'Papúa Nueva Guinea',
  PY: 'Paraguay',
  PE: 'Perú',
  PH: 'Filipinas',
  PN: 'Islas Pitcairn',
  PL: 'Polonia',
  PT: 'Portugal',
  PR: 'Puerto Rico',
  QA: 'Qatar',
  CZ: 'República Checa',
  CG: 'República del Congo',
  DO: 'República Dominicana',
  RO: 'Rumanía',
  RU: 'Rusia',
  RW: 'Ruanda',
  BL: 'San Bartolomé',
  SH: 'Santa Elena',
  KN: 'San Cristóbal y Nieves',
  LC: 'Santa Lucía',
  MF: 'San Martín',
  WS: 'Samoa Occidental',
  SM: 'San Marino',
  SN: 'Senegal',
  RS: 'Serbia y Montenegro',
  CS: 'Serbia',
  SC: 'Seychelles',
  SL: 'Sierra Leona',
  SG: 'Singapur',
  SX: 'San Martín',
  SK: 'Eslovaquia',
  SI: 'Eslovenia',
  SB: 'Islas Salomón',
  SO: 'Somalia',
  ZA: 'Sudáfrica',
  GS: 'Georgia del Sur e Islas Sandwich del Sur',
  KR: 'Corea del Sur',
  SS: 'Sudán del Sur',
  ES: 'España',
  LK: 'Sri Lanka',
  SD: 'Sudán',
  SR: 'Surinam',
  SJ: 'Islas Svalbard y Jan Mayen',
  SZ: 'Suazilandia',
  SE: 'Suecia',
  CH: 'Suiza',
  SY: 'Siria',
  TW: 'Taiwán',
  TJ: 'Tayikistán',
  TZ: 'Tanzania',
  TH: 'Tailandia',
  TG: 'República Togolesa',
  TK: 'Islas Tokelau',
  TO: 'Tonga',
  TT: 'Trinidad y Tobago',
  TN: 'Túnez',
  TR: 'Turquía',
  TM: 'Turkmenistán',
  TC: 'Islas Turcos y Caicos',
  TV: 'Tuvalu',
  VI: 'Islas Vírgenes de los EE.UU.',
  UG: 'Uganda',
  UA: 'Ucrania',
  AE: 'Emiratos Árabes Unidos',
  GB: 'Reino Unido',
  US: 'Estados Unidos',
  UM: 'Islas menores alejadas de los Estados Unidos',
  UY: 'Uruguay',
  UZ: 'Uzbekistán',
  VU: 'Vanuatu',
  VA: 'Vaticano',
  VE: 'Venezuela',
  VN: 'Vietnam',
  WF: 'Wallis y Futuna',
  EH: 'Sahara Occidental',
  YE: 'Yemen',
  ZM: 'Zambia',
  ZW: 'Zimbabue',
};

export const backgrounds: object | any = {
  '01d': { back: '#3b7adf', text: '#000', hora: 'Día' },
  '01n': { back: '#11265a', text: '#fff', hora: 'Noche' },
  '02d': { back: '#32509e', text: '#000', hora: 'Día' },
  '02n': { back: '#29385d', text: '#fff', hora: 'Noche' },
  '03d': { back: '#96a3c5', text: '#000', hora: 'Día' },
  '03n': { back: '#4d5569', text: '#fff', hora: 'Noche' },
  '04d': { back: '#8a909c', text: '#000', hora: 'Día' },
  '04n': { back: '#5e636b', text: '#fff', hora: 'Noche' },
  '09d': { back: '#8a909c', text: '#000', hora: 'Día' },
  '09n': { back: '#5e636b', text: '#fff', hora: 'Noche' },
  '10d': { back: '#b2a5db', text: '#000', hora: 'Día' },
  '10n': { back: '#655f7a', text: '#fff', hora: 'Noche' },
  '11d': { back: '#626262', text: '#000', hora: 'Día' },
  '11n': { back: '#494949', text: '#fff', hora: 'Noche' },
  '13d': { back: '#a1d0f0', text: '#000', hora: 'Día' },
  '13n': { back: '#516a81', text: '#fff', hora: 'Noche' },
  '50d': { back: '#9fa2a3', text: '#000', hora: 'Día' },
  '50n': { back: '#6a6b6d', text: '#fff', hora: 'Noche' },
};
